✨ Add Spring Security
PANTS-GOORM/BackEnd pull request #38
Opened 2024-04-15 07:22 UTC by Inbeom-970210

- Spring Security OAuth2 추가
- JWT 적용

2024-04-15 07:35 UTC, chickennight requested changes

2024-04-15 07:35 UTC, chickennight commented on src/main/java/com/goorm/wordsketch/repository/UserRepository.java
> +    Optional<User> findByNickname(String nickanme);
nickanme?
nickname 아닌가요?

2024-04-15 07:35 UTC, chickennight commented on src/main/java/com/goorm/wordsketch/service/CustomOAuth2UserService.java
> +        System.out.println("userRequest = " + userRequest);
로그 지워주세요.

2024-04-15 07:35 UTC, chickennight commented on src/main/java/com/goorm/wordsketch/service/CustomOAuth2UserService.java
> +        System.out.println("response = " + response);
확인용 로그

2024-04-15 07:35 UTC, chickennight commented on src/main/java/com/goorm/wordsketch/service/JwtService.java
> +        System.out.println("authentication.getName() = " + authentication.getName());
위와 같습니다

2024-04-15 07:35 UTC, chickennight commented on src/main/java/com/goorm/wordsketch/util/JwtTokenValidatorFilter.java
> +        System.out.println(path.startsWith("/login/oauth2") || path.startsWith("/kauth") || "/".equals(path) || "/favicon.ico".equals(path));
로그 확인용 없애주세요

2024-04-15 07:41 UTC, jvlover requested changes

2024-04-15 07:41 UTC, jvlover commented on src/main/java/com/goorm/wordsketch/config/SecurityConfig.java
> +    private JwtTokenValidatorFilter jwtTokenValidatorFilter;
Autowired 어노테이션은 생성자에 달아주는 것이 권장됩니다!

2024-04-15 07:55 UTC, Inbeom-970210 commented on src/main/java/com/goorm/wordsketch/repository/UserRepository.java
> +    Optional<User> findByNickname(String nickanme);
ㅠㅠ 왼손이 빨랐네

2024-04-15 08:01 UTC, chickennight commented on src/main/java/com/goorm/wordsketch/entity/User.java
> +    @Column(name = "profile_img_url", nullable = false, columnDefinition = "VARCHAR(300)")
프로필 이미지가 null이 불가능하면 이미지 입력 없이는 회원가입이 안되는거 같은데 괜찮나요?

2024-04-15 08:19 UTC, Inbeom-970210 commented on src/main/java/com/goorm/wordsketch/entity/User.java
> +    @Column(name = "profile_img_url", nullable = false, columnDefinition = "VARCHAR(300)")
프로필 없으면 기본 이미지 주잖아. 그거 주더라고

2024-04-15 08:19 UTC, Inbeom-970210 commented on build.gradle
> +version = '0.1.6-SNAPSHOT'  // main에 merge할 때는 업그레이드 필요!! 버전 체크 필요!!
해치웠습니다!

2024-04-15 08:20 UTC, Inbeom-970210 commented on src/main/java/com/goorm/wordsketch/service/CustomOAuth2UserService.java
> +            System.out.println("hash = " + hash);
ㅠㅠ

2024-04-15 08:20 UTC, Inbeom-970210 commented on src/main/java/com/goorm/wordsketch/config/SecurityConfig.java
> +    private JwtTokenValidatorFilter jwtTokenValidatorFilter;
이 친구들도 바꿔야지

2024-04-16 01:22 UTC, chickennight commented on src/main/java/com/goorm/wordsketch/entity/User.java
> +    @Column(name = "profile_img_url", nullable = false, columnDefinition = "VARCHAR(300)")
굿

2024-04-16 02:48 UTC, chickennight commented
version 0.1.7 로 업해주시면 되고, 머지하기 전에 git pull origin main 하고 컨플릭 해결후 해주시면 됩니다..
application-prod.yml 파일에 ddl-auto를 update로 바꿔주시면 됩니다

2024-04-16 03:40 UTC, chickennight approved these changes

2024-04-16 03:40 UTC, merged